bind_on = "localhost:3000"
work_period_minutes = 40
break_minutes = 1

[[requirements]]
name = "Drink 1"
due = "7:30"

[[requirements]]
name = "Charge phone"
due = "19:00"

[[requirements]]
name = "Drink 2"
due = "19:30"

[[requirements]]
name = "Floss"
due = "20:00"

[[requirements]]
name = "Brush teeth"
due = "20:00"

[[locked_time_ranges]]
end = "5:30"

[[locked_time_ranges]]
start = "23:00"
