diagonator_path = "/home/yaxollum/.local/bin/diagonator"
diagonator_args = [
    "--top-margin",
    "50",
]
socket_path = "/tmp/diagonator-server.sock"
work_period_minutes = 25
break_minutes = 5

[[requirements]]
name = "Prepare to leave"
due = "8:10"

[[requirements]]
name = "Brush teeth"
due = "19:30"

[[requirements]]
name = "Wash face"
due = "19:30"

[[requirements]]
name = "Prepare bread"
due = "19:30"

[[requirements]]
name = "Start flossing"
due = "19:30"

[[requirements]]
name = "Target bedtime"
due = "20:30"

[[requirements]]
name = "Target bedtime 2"
due = "21:30"

[[requirements]]
name = "Target bedtime 3"
due = "22:30"

[[requirements]]
name = "Target bedtime 4"
due = "23:30"

