diagonator_path = "/home/yaxollum/.local/bin/diagonator"
diagonator_args = [
    "--top-margin",
    "50",
]
socket_path = "/tmp/diagonator-server.sock"
work_period_minutes = 25
break_minutes = 5

[[requirements]]
name = "Brush teeth"
due = "20:00"

[[requirements]]
name = "Wash face"
due = "20:00"

[[requirements]]
name = "Prepare bread"
due = "20:00"

[[requirements]]
name = "Start flossing"
due = "20:00"

[[locked_time_ranges]]
end = "04:30"

[[locked_time_ranges]]
start = "21:30"
