diagonator_path = "/home/yaxollum/.local/bin/diagonator"
diagonator_args = [
    "--top-margin",
    "40",
]
socket_path = "/tmp/diagonator-server.sock"
work_period_minutes = 40
break_minutes = 1

[[requirements]]
name = "Drink 1"
due = "7:30"

[[requirements]]
name = "Charge phone"
due = "19:00"

[[requirements]]
name = "Drink 2"
due = "19:30"

[[requirements]]
name = "Floss"
due = "20:00"

[[requirements]]
name = "Brush teeth"
due = "20:00"

[[requirements]]
name = "Target bedtime"
due = "23:00"

[[locked_time_ranges]]
end = "7:00"

[[locked_time_ranges]]
start = "23:30"
