diagonator_path = "/home/yaxollum/.local/bin/diagonator"
diagonator_args = [
    "--top-margin",
    "50",
]
socket_path = "/tmp/diagonator-server.sock"
work_period_minutes = 60
break_minutes = 1

[[requirements]]
name = "Drink 1"
due = "7:30"

[[requirements]]
name = "Charge phone"
due = "16:30"

[[requirements]]
name = "Drink 2"
due = "19:30"

[[requirements]]
name = "Brush teeth"
due = "20:00"

[[requirements]]
name = "Start flossing"
due = "20:00"

[[requirements]]
name = "Target bedtime"
due = "22:30"

[[requirements]]
name = "Target bedtime 2"
due = "23:30"

